### ISSUE TITLE
UI Bug with Accordion

### ISSUE THREAD

**Issue by aditya172926** [aditya172926/BlockOverflow_frontend#1]
We require something similar to dynamically setting the Id's of each accordion button. The current bug is that when the accordion is clicked to open, all the accordions for other questions open as well.

Each accordion to a question must be unique to it.

**Comment by KishoreVB70** [comment]
done

**Comment by KishoreVB70** [comment]
I'm working on this Issue.

**Comment by aditya172926** [comment]
The UI bug for accordion is solved and merged in the main branch.
