### ISSUE TITLE
Wrap the doubt input into a modal

### ISSUE THREAD

**Issue by KishoreVB70** [aditya172926/BlockOverflow_frontend#5]
Wrap the doubt posting form into a modal.
Add a separate button at an appropriate position in the UI to access this modal.

**Comment by aditya172926** [comment]
Instead of creating 2 separate modals for displaying answer and writing answer, create just 1 modal and using a ternary operator change the form content of the modal according to the button clicked.

**Comment by aditya172926** [comment]
Test the PR #9 and if successful merge to main.

**Comment by aditya172926** [comment]
PR is merged.
